project:
  name: quickstart-eks-PPNAMELD
  owner: quickstart-eng@amazon.com
  regions: ["us-west-2"]
  template: templates/eks-PPNAMELD.template.yaml
  parameters:
    Namespace: [taskcat_random-string]
tests:
  default: {}