AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys PPNAME into an existing kubernetes cluster (QSID)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing EKS cluster"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: PPNAME for EKS configuration
        Parameters:
          - KubeClusterName
          - Namespace
    ParameterLabels:
      KubeClusterName:
        default: EKS cluster name
      Namespace:
        default: Namespace
Parameters:
  KubeClusterName:
    Type: String
    Description: Name of the EKS cluster to deploy PPNAME into.
  Namespace:
    Type: String
PPNAMEE
    Description: '[Optional] Kubernetes namespace to deploy PPNAME into.'
Resources:
  PPNAMENamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Manifest: |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: !Ref Namespace
  PPNAMEHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref KubeClusterName
      Namespace: !GetAtt PPNAMENamespace.Name
      Chart: repo/chart
      Name: PPNAME
Outputs:
  PPNAMEReleaseName:
    Value: !GetAtt PPNAMEHelmChart.Name

